# Generated by Django 3.1 on 2021-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriptoValores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.PositiveSmallIntegerField(choices=[(1, 'BRLBTC'), (2, 'BRLETH')], db_index=True, verbose_name='Pair')),
                ('mms_timestamp', models.BigIntegerField(db_index=True, verbose_name='Timestamp')),
                ('close', models.DecimalField(decimal_places=5, max_digits=16, verbose_name='Valor do fechamento diario')),
                ('mms_20', models.DecimalField(decimal_places=5, default=0, max_digits=16, verbose_name='Mms 20 dias')),
                ('mms_50', models.DecimalField(decimal_places=5, default=0, max_digits=16, verbose_name='Mms 50 dias')),
                ('mms_200', models.DecimalField(decimal_places=5, default=0, max_digits=16, verbose_name='Mms 200 dias')),
            ],
        ),
    ]
